language: ruby
rvm:
  - 2.1.2

before_install:
  - sudo apt-get update
  - sudo apt-get upgrade -y
  - sudo apt-get install -y webp

  - git config --global user.email "enyriel@gmail.com"
  - git config --global user.name "Aurélien Léger"

branches:
  only:
    - master

script:
  - bundle exec middleman build
  - bundle exec middleman deploy

